= Couchbase Tabs Extension (Non-working) Example
:tabs:

This page shows how to implement tab pages using the tabs-block.js extension at https://github.com/couchbase/docs-site/blob/master/lib/tabs-block.js.

It extends the AsciiDoc syntax to support a tabset. The tabset is created from a definition list enclosed in an example block that is marked with the tabs style.

For instructions, see https://docs.couchbase.com/home/contribute/tabs.html.

== Dan Allen's example
From https://twitter.com/i/web/status/1046666053449728000
or https://threadreaderapp.com/thread/1046666053449728000.html

[tabs]
====
Tab A::
+
--
Tab A contents
--
Tab B::
+
--
Tab B contents
--
====

== Test 1

[{tabs}]
====
Tab A::
+
--
Contents of tab A.

* one
* two
* three
--

Tab B::
+
--
Contents of tab B.

. one
. two
. three
--
====

a line between

== Test 2

[{tabs}]
====
Tab 1 Title::
+
--

This is the content of the first tab.

Another paragraph in the first tab.

[source,console]
----
$ a code block
----
--

Tab 2 Title::
+
--
This is the content of the second tab.
--
====

== What I did to implement this

. I copied *tabs-block.js* from the couchbase website to my *lib* folder.
. I added an entry for *tabs-block.js* to my playbook:
. I downloaded Dan Allen's tabs-block extension. For some reason, behavior.js and extension.js throw errors when added to the extensions seciton of my playbook, so I commented those out.
. I copied Dan Allen's *styles.css* to the source/css folder in my experimental UI bundle.
. I appended @import *"styles.css";* to site.css.
. I packed the ui bundle.
. Generated the site. At this point the tabs look right, but nothing happens when clicked. I probably need to add behavior.js and extension.js.
. In my UI bundle, under src/js I created a folder named tab-block, and put behavior.js and extension.js in it.
. I appended these lines to *footer-scripts.hbs* in the ui bundle
+
<script src="{{uiRootPath}}/js/tab-block/behavior.js"></script>
<script src="{{uiRootPath}}/js/tab-block/extension.js"></script>
. I packed the ui bundle again. But pack failed with errors (Opal) in extension.js. I removed extension.js. Pack succeeded. But tabs still do not select.
. I am stumped for now.
