= Couchbase Tabs Extension Example
:tabs:

This page shows how to implement tab pages using the tabs-block.js extension at https://github.com/couchbase/docs-site/blob/master/lib/tabs-block.js.

It extends the AsciiDoc syntax to support a tabset. The tabset is created from a definition list enclosed in an example block that is marked with the tabs style.

For instructions, see https://docs.couchbase.com/home/contribute/tabs.html.

[{tabs}]
====
Tab A::
+
--
Contents of tab A.

* one
* two
* three
--

Tab B::
+
--
Contents of tab B.

. one
. two
. three
--
====

a line between

== Test

[{tabs}]
====
Tab 1 Title::
+
--

This is the content of the first tab.

Another paragraph in the first tab.

[source,console]
----
$ a code block
----
--

Tab 2 Title::
+
--
This is the content of the second tab.
--
====

++++
<style>
/*
.doc .tabs ul {
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    list-style: none;
    margin: 0 -.25rem 0 0;
    padding: 0
}

.doc .tabs li,
.doc .tabs ul {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex
}

.doc .tabs li {
    -webkit-box-align: center;
    -ms-flex-align: center;
    align-items: center;
    border: 1px solid #c1c1c1;
    border-bottom: 0;
    cursor: pointer;
    font-weight: 700;
    height: 2.5rem;
    line-height: 1;
    margin-right: .25rem;
    padding: 0 1.5rem;
    position: relative
}

.doc .tabs li+li {
    margin-top: 0
}

.doc .tabset.is-loading .tabs li:not(:first-child),
.doc .tabset:not(.is-loading) .tabs li:not(.is-active) {
    background-color: #333;
    color: #fff
}

.doc .tabset.is-loading .tabs li:first-child:after,
.doc .tabs li.is-active:after {
    background-color: #fff;
    content: "";
    display: block;
    height: 3px;
    position: absolute;
    bottom: -1.5px;
    left: 0;
    right: 0
}

.doc .tabset>.content {
    border: 1px solid #c1c1c1;
    padding: 1.25rem
}

.doc .tabset.is-loading .tab-pane:not(:first-child),
.doc .tabset:not(.is-loading) .tab-pane:not(.is-active) {
    display: none
}

.doc .tab-pane>:first-child {
    margin-top: 0
}
*/
/* begin new */
.tabs ul {
  display: flex;
  flex-wrap: wrap;
  list-style: none;
  margin: 0 -0.25rem 0 0;
  padding: 0;
}

.tabs li {
  align-items: center;
  border: 1px solid black;
  border-bottom: 0;
  cursor: pointer;
  display: flex;
  font-weight: bold;
  height: 2.5rem;
  line-height: 1;
  margin-right: 0.25rem;
  padding: 0 1.5rem;
  position: relative;
}

.tabs.ulist li {
  margin-bottom: 0;
}

.tabs li + li {
  margin-top: 0;
}

.tabset.is-loading .tabs li:not(:first-child),
.tabset:not(.is-loading) .tabs li:not(.is-active) {
  background-color: black;
  color: white;
}

.tabset.is-loading .tabs li:first-child::after,
.tabs li.is-active::after {
  background-color: white;
  content: "";
  display: block;
  height: 3px; /* Chrome doesn't always paint the line accurately, so add a little extra */
  position: absolute;
  bottom: -1.5px;
  left: 0;
  right: 0;
}

.tabset > .content {
  border: 1px solid gray;
  padding: 1.25rem;
}

.tabset.is-loading .tab-pane:not(:first-child),
.tabset:not(.is-loading) .tab-pane:not(.is-active) {
  display: none;
}

.tab-pane > :first-child {
  margin-top: 0;
}
</style>

<script>
;(function () {
  'use strict'

  var hash = window.location.hash
  find('.tabset').forEach(function (tabset) {
    var active
    var tabs = tabset.querySelector('.tabs')
    if (tabs) {
      var first
      find('li', tabs).forEach(function (tab, idx) {
        var id = (tab.querySelector('a[id]') || tab).id
        if (!id) return
        var pane = getPane(id, tabset)
        if (!idx) first = { tab: tab, pane: pane }
        if (!active && hash === '#' + id && (active = true)) {
          tab.classList.add('is-active')
          if (pane) pane.classList.add('is-active')
        } else if (!idx) {
          tab.classList.remove('is-active')
          if (pane) pane.classList.remove('is-active')
        }
        tab.addEventListener('click', activateTab.bind({ tabset: tabset, tab: tab, pane: pane }))
      })
      if (!active && first) {
        first.tab.classList.add('is-active')
        if (first.pane) first.pane.classList.add('is-active')
      }
    }
    tabset.classList.remove('is-loading')
  })

  function activateTab (e) {
    var tab = this.tab
    var pane = this.pane
    find('.tabs li, .tab-pane', this.tabset).forEach(function (it) {
      it === tab || it === pane ? it.classList.add('is-active') : it.classList.remove('is-active')
    })
    e.preventDefault()
  }

  function find (selector, from) {
    return Array.prototype.slice.call((from || document).querySelectorAll(selector))
  }

  function getPane (id, tabset) {
    return find('.tab-pane', tabset).find(function (it) {
      return it.getAttribute('aria-labelledby') === id
    })
  }
})()
</script>
++++
