= Landing page example
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

++++
<div class="row">
  <div class="column">
    <div class="card">
    <p style="text-align:center;"><strong>AsciiDoc</strong></p>
    <hr>
    <p>Learn to write in AsciiDoc today</p>
    </div>
  </div>
  <div class="column">
    <div class="card">
        <p style="text-align:center;"><strong>Antora</strong></p>
      <hr>
      <p>Build a website from AsciiDoc files</p>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <p style="text-align:center;"><strong>Sustainable Living</strong></p>
    <hr>
    <p>Things we can All do to live better</p>
    </div>
  </div>
  <div class="column">
    <div class="card">
      <p style="text-align:center;"><strong>Blog</strong></p>
    <hr>
    <p>Articles and Opinions</p>
    </div>
  </div>
</div>

<style>
* {
  box-sizing: border-box;
}

#body {
#  font-family: Arial, Helvetica, sans-serif;
#}

/* Float four columns side by side */
.column {
  float: left;
  width: 25%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding in columns */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Style the counter cards */
.cardORG {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); /* this adds the "card" effect */
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}

/* Responsive columns - one column layout (vertical) on small screens */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

.card {
  position: relative;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
  /* Special styling for 2nd level landing page cards */
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); /* this adds the "card" effect */
  padding: 16px;
  text-align: left;
  background-color: #f1f1f1;
}
</style>
++++
